# Site settings
title: The Accidental Chiapet
email: emily.j.willson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
            A blog on life, love, and embracing the groutfit. 
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: emjoywill
github_username:  emjoywill

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  #portfolio:
  #   output: true
  #   permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


