# Site settings
title: The Accidental Chiapet
email: emily.j.willson@gmail.com
description: A blog about life, work, and embracing the groutfit. 
baseurl:  # the subpath of your site, e.g. /blog/
url: http://accidentalchiapet.com  # the base hostname & protocol for your site
author: Emily Willson and Julia Hensel

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  #portfolio:
  #   output: true
  #   permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


